### ISSUE TITLE
최대 몇 페이지까지의 정보를 받아 올껀가요?

### ISSUE THREAD

**Issue by lee3604** [4xvgal/JobScraper#15]
10페이지 까지 있다면 10페이지 전체 다 불러오나요 아니면 
일정 범위를 초과하면 정해진 페이지 만큼의 정보만 크롤링 하나요?

**Comment by 4xvgal** [comment]
혹은 구인글 작성일자가 최신인것만 스크래핑 하는것은 어떨까요?
90일이 지난 글은 오래되어 쓸모가 없다고 생각합니다.

**Comment by gwon9906** [comment]
마감일이 지나지 않은 공고만 올라오는 것 같아서 일단은 페이지 수를 구할 수 있는 코드를 추가했습니다.

**Comment by hyenie1** [comment]
cp-info를 통해서 
정규직경력학력무관연봉 회사 내규에 따름 - > 이부분만 가져오려고 하는데
text[0]을 통해서 가져와지지가 않네요 [1]을 통해서 근무지 서울 강남구정보제공처 : 잡코리아를 가져오는건 가능한데
햄들 도와주십쇼

**Comment by gwon9906** [comment]
그거 인덱스 1부터 시작이에요
